# Generated by Django 3.0.7 on 2021-11-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
    ]
