# Generated by Django 3.0.7 on 2021-11-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapi', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_review', to='demoapi.Movie'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_votes', to='demoapi.Movie'),
        ),
    ]
